

services:
  client:
    build: ./hoodie-nation-app
    ports:
      - "5174:5173"  # Host:Container
    volumes:
      - ./hoodie-nation-app:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./service
    ports:
      - "5000:5000"
    volumes:
      - ./service:/app
      - /app/node_modules
    env_file:
      - ./service/.env
    depends_on:
      - db

  db: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: hnation-db
    ports:
      - "5434:5433" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
